### ISSUE TITLE
Учет и хранение документов

### ISSUE THREAD

**Issue by kimspark** [UGTU/Old-School#78]
Сканирование личных документов абитуриентов и введение их в программу при приеме заявлений абитуриентов (документ удостоверяющий личность, документ об образовании, для льготной категории граждан документы подтверждающие льготу и другие при необходимости).

**Comment by reb00ter** [comment]
Сразу оговорим, что документы сканируются сетевым принтером в отдельную папку для каждого пользователя (у них раскидаем ярлыки)
