### ISSUE TITLE
«Адрес электронной почты» сделать не обязательным

### ISSUE THREAD

**Issue by kimspark** [UGTU/Old-School#84]

**Comment by reb00ter** [comment]
С этим уже определились точно?

**Comment by kimspark** [comment]
Приемная комиссия в служебке это написала (они всю кампанию 2014 придумывали фейковые адреса для тех, у кого E-mail отсутствует). С другой стороны, это требование Центра ДО было. С ними тоже нужно обсудить, наверное.

**Comment by reb00ter** [comment]
ну вообще с ними должна обсуждать ПК как раз..
