### ISSUE TITLE
Проблема дипломов: ряд данных не отображается

### ISSUE THREAD

**Issue by kimspark** [UGTU/Old-School#90]
Пример: ЭП-11 (Экология и природопользование).
1) Не отражается в дипломе школа
2) Не отражается Учебная практика (гидрометеорологическая)

**Comment by tanvok** [comment]
Чтобы отображались данные о пред образовании, нужно заполнить документы об образовании - аттестат (потому что выводится вид документа).

**Comment by tanvok** [comment]
Практики не отображались потому что названия дисциплины по диплому не было (я заполнила для всех дисциплин, которые не были заполнены из просто названия).

**Comment by kimspark** [comment]
Таня молодец :)

2015-04-08 16:32 GMT+03:00 tanvok notifications@github.com:

> Практики не отображались потому что названия дисциплины по диплому не было
> (я заполнила для всех дисциплин, которые не были заполнены из просто
> названия).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UGTU/Old-School/issues/90#issuecomment-90917390.

## 

Best wishes.

Kim Spark
